# mbake configuration file

[formatter]
auto_insert_phony_declarations = true
ensure_final_newline = true
fix_missing_recipe_tabs = true
group_phony_declarations = true
indent_nested_conditionals = true
max_consecutive_empty_lines = 2
max_line_length = 120
normalize_empty_lines = true
normalize_line_continuations = true
phony_at_top = false
remove_trailing_whitespace = true
space_after_colon = true
space_around_assignment = true
space_before_colon = false
tab_width = 2
