extends: default
rules:
  document-start: disable
  line-length: disable
  truthy: # https://github.com/adrienverge/yamllint/issues/666#issuecomment-2034469482
    check-keys: false
  comments:
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 1
    ignore: |
      .github/workflows/release-drafter.yml
ignore: |
  test_*.yml
