name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE [#$NUMBER](https://github.com/gdsfactory/quantum-rf-pdk/pull/$NUMBER)'
template: |
  # What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
categories:
  - title: 'Breaking'
    label: 'breaking'
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'components'
      - 'models'
      - 'technology'
  - title: 'Bug Fixes'
    label: 'bug'
  - title: 'Documentation'
    labels:
      - 'documentation'
      - 'notebooks'
  - title: 'Dependency Updates'
    label: 'dependencies'
    collapse-after: 5
  - title: 'Other Changes'
    labels:
      - 'maintenance'
      - 'tests'
      - 'ci'
      - 'infrastructure'
      - 'samples'
version-resolver:
  major:
    labels:
      - 'breaking'
      - 'major'
  minor:
    labels:
      - 'feature'
      - 'minor'
      - 'enhancement'
      - 'components'
      - 'models'
      - 'technology'
  patch:
    labels:
      - 'bug'
      - 'maintenance'
      - 'github_actions'
      - 'documentation'
      - 'dependencies'
      - 'security'
      - 'tests'
      - 'samples'
      - 'notebooks'
      - 'ci'
      - 'infrastructure'
  default: patch
exclude-labels:
  - 'skip-changelog'
autolabeler:
  - label: 'documentation'
    files:
      - '*.md'
      - 'docs/**/*'
  - label: 'notebooks'
    files:
      - '*.ipynb'
      - 'qpdk/notebooks/**/*'
  - label: 'components'
    files:
      - 'qpdk/cells/**/*'
  - label: 'models'
    files:
      - 'qpdk/models/**/*'
  - label: 'technology'
    files:
      - 'qpdk/tech.py'
      - 'qpdk/layers.yaml'
      - 'qpdk/klayout/**/*'
  - label: 'tests'
    files:
      - 'tests/**/*'
      - 'test_*.py'
      - '*_test.py'
  - label: 'dependencies'
    files:
      - 'pyproject.toml'
      - 'uv.lock'
      - 'requirements*.txt'
    title:
      - '/dep/i'
      - '/update/i'
      - '/bump/i'
  - label: 'bug'
    title:
      - '/fix/i'
      - '/bug/i'
  - label: 'feature'
    title:
      - '/feature/i'
      - '/add/i'
      - '/enhance/i'
      - '/improve/i'
