name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE [#$NUMBER](https://github.com/gdsfactory/quantum-rf-pdk/pull/$NUMBER)'
template: |
  # What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
categories:
  - title: 'Breaking'
    label: 'breaking'
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'components'
      - 'models'
      - 'technology'
  - title: 'Bug Fixes'
    label: 'bug'
  - title: 'Documentation'
    labels:
      - 'documentation'
      - 'notebooks'
  - title: 'Dependency Updates'
    label: 'dependencies'
    collapse-after: 5
  - title: 'Other Changes'
    labels:
      - 'maintenance'
      - 'tests'
      - 'ci'
      - 'infrastructure'
      - 'samples'
version-resolver:
  major:
    labels:
      - 'breaking'
      - 'major'
  minor:
    labels:
      - 'feature'
      - 'minor'
      - 'enhancement'
      - 'components'
      - 'models'
      - 'technology'
  patch:
    labels:
      - 'bug'
      - 'maintenance'
      - 'github_actions'
      - 'documentation'
      - 'dependencies'
      - 'security'
      - 'tests'
      - 'samples'
      - 'notebooks'
      - 'ci'
      - 'infrastructure'
  default: patch
exclude-labels:
  - 'skip-changelog'
