rules:
  unpinned-uses:
    ignore:
      - "issue.yml"
      - "pages.yml"
      - "release-drafter.yml"
  dangerous-triggers:
    ignore:
      - "pages.yml"
  artipacked:
    disable: true
  template-injection:
    disable: true
