repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        exclude: ^(conda\.recipe/meta\.yaml|conda_build/templates/.*\.yaml|docs/click/meta\.yaml|conda/meta\.yaml|conda/construct.yaml|.*\.pic\.yml|conda/constructor/Miniforge3/construct.yaml)
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
        files: ".ipynb"
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.12.10"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --config=pyproject.toml]
      - id: ruff-format
        args: [--config=pyproject.toml]
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.15.0
    hooks:
      - id: pretty-format-toml
        args: [--autofix]
  - repo: https://github.com/aristanetworks/j2lint.git
    rev: v1.2.0
    hooks:
      - id: j2lint
        types: [file]
        files: \.(j2|yml|yaml)$
        exclude: .github/.*
  - repo: https://github.com/google/yamlfmt
    rev: v0.17.2
    hooks:
      - id: yamlfmt
        args: [-conf, ".github/.yamlfmt.yaml"]
        exclude: ".*.tests*|.*.pic.yml"
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.13
    hooks:
      - id: uv-lock
  - repo: https://github.com/facebook/pyrefly-pre-commit
    rev: 0.0.1
    hooks:
      - id: pyrefly-typecheck-specific-version
        name: Pyrefly
        pass_filenames: false
        additional_dependencies: ["pyrefly==0.32.0"]
  - repo: https://github.com/FlamingTempura/bibtex-tidy
    rev: v1.14.0
    hooks:
      - id: bibtex-tidy
        args: ['--align=1', '--curly', '--months', '--sort', '--duplicates', '--strip-enclosing-braces']
  - repo: https://github.com/AleksaC/hadolint-py
    rev: v2.13.1
    hooks:
      - id: hadolint
  - repo: https://github.com/checkmake/checkmake.git
    rev: 0.2.2
    hooks:
      - id: checkmake
        args: ['--config=.github/.checkmake.ini']
