repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        exclude: ^(conda\.recipe/meta\.yaml|conda_build/templates/.*\.yaml|docs/click/meta\.yaml|conda/meta\.yaml|conda/construct.yaml|.*\.pic\.yml|conda/constructor/Miniforge3/construct.yaml)
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
        files: ".ipynb"
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.13.2"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --config=pyproject.toml]
      - id: ruff-format
        args: [--config=pyproject.toml]
  - repo: https://github.com/tombi-toml/tombi-pre-commit
    rev: v0.6.39
    hooks:
      - id: tombi-format
      - id: tombi-lint
  - repo: https://github.com/aristanetworks/j2lint.git
    rev: v1.2.0
    hooks:
      - id: j2lint
        types: [file]
        files: \.(j2|yml|yaml)$
        exclude: .github/.*
        args: [--ignore, jinja-statements-delimiter, single-statement-per-line, jinja-statements-indentation, --]
  - repo: https://github.com/google/yamlfmt
    rev: v0.17.2
    hooks:
      - id: yamlfmt
        args: [-conf, ".github/.yamlfmt.yaml"]
        exclude: &regression_tests ".*.tests*"
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        args: [--strict, "-c=.github/.yamllint.yaml"]
        exclude: *regression_tests
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.22
    hooks:
      - id: uv-lock
  - repo: https://github.com/facebook/pyrefly-pre-commit
    rev: 0.0.1
    hooks:
      - id: pyrefly-typecheck-specific-version
        name: Pyrefly
        pass_filenames: true
        additional_dependencies: ["pyrefly==0.34.0"]
        # Pre-commit may not have access to all deps.
        args: ["--ignore", "import-error"]
  - repo: https://github.com/FlamingTempura/bibtex-tidy
    rev: v1.14.0
    hooks:
      - id: bibtex-tidy
        args: ['--align=1', '--curly', '--months', '--sort', '--duplicates', '--strip-enclosing-braces']
  - repo: https://github.com/AleksaC/hadolint-py
    rev: v2.14.0
    hooks:
      - id: hadolint
  - repo: https://github.com/checkmake/checkmake.git
    rev: 0.2.2
    hooks:
      - id: checkmake
        args: ['--config=.github/.checkmake.ini']
  - repo: https://github.com/EbodShojaei/bake
    rev: v1.4.1.pre
    hooks:
      - id: mbake-validate
      - id: mbake-format
        args: ['--config=.github/.bake.toml']
  - repo: https://github.com/LilSpazJoekp/docstrfmt
    rev: v1.11.1
    hooks:
      - id: docstrfmt
        language_version: python3
        types: [rst]
  - repo: https://github.com/sphinx-contrib/sphinx-lint
    rev: v1.0.0
    hooks:
      - id: sphinx-lint
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
      - id: markdownlint-cli2
        name: markdownlint
        args: [--config, .github/.markdownlint-cli2.yaml]
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        args: [--wrap=120]
        additional_dependencies:
          - mdformat-gfm
          - mdformat-gfm-alerts
          - mdformat-tables
          - mdformat-frontmatter
          - mdformat-footnote
  - repo: https://github.com/econchick/interrogate
    rev: 1.7.0
    hooks:
      - id: interrogate
        args: [--config=pyproject.toml]
        pass_filenames: true
        exclude: '^(?:docs/_build/.*|qpdk(?:/.*)?/__init__[.]py|notebooks/.*|docs/notebooks/[^/]+|qpdk/samples/[^/]+[.]py|tests/.*)$'
  - repo: local
    hooks:
      - id: convert-notebooks
        name: Convert jupytext notebooks
        entry: ./.github/convert-notebooks.sh
        language: script
        files: ^notebooks/src/.*\.py$
        pass_filenames: true
