name: Feature Request
description: Suggest a new feature or enhancement for quantum-rf-pdk
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when... / It would be helpful if...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: Describe your proposed feature...
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - New quantum device component
        - New routing/waveguide feature
        - Simulation model enhancement
        - Documentation improvement
        - Testing enhancement
        - Performance improvement
        - KLayout integration
        - API enhancement
        - Other
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: Alternative approaches...
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your use case and how this feature would benefit you or others
      placeholder: This would be useful for...
    validations:
      required: true
  - type: textarea
    id: implementation
    attributes:
      label: Implementation Suggestions
      description: If you have ideas about how to implement this, please share them
      placeholder: |
        This could be implemented by...
        - Adding a new component in qpdk/cells/
        - Modifying existing routing functions
        - etc.
  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: If applicable, show how you envision using this feature
      placeholder: |
        ```python
        import qpdk

        # Example of how the feature would be used
        component = qpdk.components.new_feature(...)
        ```
      render: python
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, diagrams, or references about the feature request
      placeholder: Any additional information...
  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      description: Please confirm the following
      options:
        - label: I have searched existing issues and pull requests to ensure this hasn't been requested before
          required: true
        - label: This feature aligns with the goals of quantum-rf-pdk
          required: false
        - label: I am willing to contribute this feature (if applicable)
          required: false
